import { Form } from "@formio/react";
import { Col, Row } from "react-bootstrap";
import { atomOneLight, CopyBlock } from "react-code-blocks";

const WizardForm = () => {
  return (
    <>
      <Row>
        <Col>
          <h2>Wizard Forms</h2>
          <p>
            Form.io provides a way to build multi-page forms and easily embed
            them within your application using the following code.
          </p>
          <CopyBlock
            text={`<Form src={'https://examples.form.io/wizard'} />`}
            theme={atomOneLight}
            language="jsx"
            codeBlock={true}
            showLineNumbers={false}
          />
          <div className="py-3">
            <Form
              src={{
                _id: "578f930ef1912f8000459a50",
                machineName: "examples:wizard",
                modified: "2023-04-25T21:16:02.821Z",
                title: "Wizard",
                display: "wizard",
                type: "form",
                name: "wizard",
                path: "wizard",
                project: "5692b91fd1028f01000407e3",
                created: "2016-07-20T15:04:46.906Z",
                components: [
                  {
                    key: "page1",
                    input: false,
                    components: [
                      {
                        type: "textfield",
                        multiple: true,
                        key: "textfieldonpage1",
                        label: "Textfield on page 1",
                        tableView: true,
                        input: true,
                      },
                      {
                        type: "number",
                        validate: { required: true },
                        defaultValue: 0,
                        key: "numberField",
                        label: "Number Field",
                        inputType: "number",
                        tableView: true,
                        input: true,
                      },
                    ],
                    title: "First",
                    type: "panel",
                    tableView: false,
                    label: "Panel",
                  },
                  {
                    tableView: false,
                    key: "page2",
                    input: false,
                    components: [
                      {
                        type: "textfield",
                        validate: { required: true },
                        key: "textfieldonPage2",
                        label: "Textfield on Page 2",
                        tableView: true,
                        input: true,
                      },
                      {
                        input: true,
                        tableView: true,
                        label: "Customer",
                        key: "page2Customer",
                        placeholder: "Select a customer",
                        data: {
                          url: "https://examples.form.io/customer/submission",
                          headers: [{ value: "", key: "" }],
                        },
                        dataSrc: "url",
                        valueProperty: "data.email",
                        template:
                          "<span>{{ item.data.firstName }} {{ item.data.lastName }}</span>",
                        type: "select",
                        widget: "html5",
                        searchField: "data.email",
                      },
                      {
                        clearOnHide: false,
                        type: "fieldset",
                        components: [
                          {
                            type: "textfield",
                            key: "textfield",
                            label: "Textfield",
                            tableView: true,
                            input: true,
                          },
                        ],
                        legend: "FieldSet Label",
                        tableView: true,
                        input: false,
                        key: "fieldSet",
                        label: "Field Set",
                      },
                    ],
                    title: "Page 2",
                    type: "panel",
                    label: "Panel",
                  },
                  {
                    type: "panel",
                    components: [
                      {
                        input: true,
                        tableView: true,
                        label: "Text",
                        key: "panelText",
                        validate: { required: true },
                        type: "textfield",
                      },
                      {
                        type: "datagrid",
                        key: "panelDataGrid",
                        label: "Data Grid",
                        tableView: true,
                        components: [
                          {
                            hideLabel: true,
                            type: "textfield",
                            key: "panelDataGridA",
                            label: "A",
                            tableView: true,
                            input: true,
                            inDataGrid: true,
                          },
                          {
                            hideLabel: true,
                            type: "textfield",
                            key: "panelDataGridB",
                            label: "B",
                            tableView: true,
                            input: true,
                            inDataGrid: true,
                          },
                          {
                            hideLabel: true,
                            type: "textfield",
                            key: "panelDataGridC",
                            label: "C",
                            tableView: true,
                            input: true,
                            inDataGrid: true,
                          },
                          {
                            hideLabel: true,
                            type: "textfield",
                            key: "panelDataGridD",
                            label: "D",
                            tableView: true,
                            input: true,
                            inDataGrid: true,
                          },
                        ],
                        input: true,
                      },
                      {
                        input: true,
                        tableView: true,
                        label: "HTML5 Select",
                        key: "panelHtml5Select",
                        data: {
                          values: [
                            { value: "orange", label: "Orange" },
                            { value: "apple", label: "Apple" },
                            { value: "banana", label: "Banana" },
                            { value: "strawberry", label: "Strawberry" },
                            { value: "kiwi", label: "Kiwi" },
                          ],
                        },
                        widget: "html5",
                        type: "select",
                      },
                    ],
                    tableView: false,
                    title: "Page 3",
                    input: false,
                    key: "panel",
                    label: "Panel",
                  },
                  {
                    key: "page3",
                    input: false,
                    components: [
                      {
                        label: "Name",
                        labelPosition: "top",
                        placeholder: "",
                        description: "",
                        tooltip: "",
                        prefix: "",
                        suffix: "",
                        widget: {
                          type: "input",
                        },
                        inputMask: "",
                        displayMask: "",
                        applyMaskOn: "change",
                        allowMultipleMasks: false,
                        customClass: "",
                        tabindex: "",
                        autocomplete: "",
                        hidden: false,
                        hideLabel: false,
                        showWordCount: false,
                        showCharCount: false,
                        mask: false,
                        autofocus: false,
                        spellcheck: true,
                        disabled: false,
                        tableView: true,
                        modalEdit: false,
                        multiple: false,
                        persistent: true,
                        inputFormat: "plain",
                        protected: false,
                        dbIndex: false,
                        case: "",
                        truncateMultipleSpaces: false,
                        encrypted: false,
                        redrawOn: "",
                        clearOnHide: true,
                        customDefaultValue: "",
                        calculateValue: "",
                        calculateServer: false,
                        allowCalculateOverride: false,
                        validateOn: "change",
                        validate: {
                          required: false,
                          pattern: "",
                          customMessage: "",
                          custom: "",
                          customPrivate: false,
                          json: "",
                          minLength: "",
                          maxLength: "",
                          strictDateValidation: false,
                          multiple: false,
                          unique: false,
                        },
                        unique: false,
                        errorLabel: "",
                        errors: "",
                        key: "name",
                        tags: [],
                        properties: {},
                        conditional: {
                          show: null,
                          when: null,
                          eq: "",
                          json: "",
                        },
                        customConditional: "",
                        logic: [],
                        attributes: {},
                        overlay: {
                          style: "",
                          page: "",
                          left: "",
                          top: "",
                          width: "",
                          height: "",
                        },
                        type: "textfield",
                        input: true,
                        refreshOn: "",
                        dataGridLabel: false,
                        addons: [],
                        inputType: "text",
                        id: "exkitqa",
                        defaultValue: "",
                      },
                      {
                        label: "DMN Rule Table",
                        labelPosition: "top",
                        placeholder: "",
                        description: "",
                        tooltip: "",
                        customClass: "",
                        tabindex: "",
                        hidden: false,
                        hideLabel: false,
                        autofocus: false,
                        disabled: false,
                        tableView: false,
                        modalEdit: false,
                        multiple: false,
                        persistent: true,
                        protected: false,
                        dbIndex: false,
                        encrypted: false,
                        redrawOn: "",
                        clearOnHide: true,
                        customDefaultValue: "",
                        calculateValue: "",
                        calculateServer: false,
                        allowCalculateOverride: false,
                        validate: {
                          required: false,
                          customMessage: "",
                          custom: "",
                          customPrivate: false,
                          json: "",
                          strictDateValidation: false,
                          multiple: false,
                          unique: false,
                        },
                        unique: false,
                        validateOn: "change",
                        errorLabel: "",
                        errors: "",
                        key: "dmnTable",
                        tags: [],
                        properties: {},
                        conditional: {
                          show: null,
                          when: null,
                          eq: "",
                          json: "",
                        },
                        customConditional: "",
                        logic: [
                          {
                            name: "name empty",
                            trigger: {
                              type: "simple",
                              simple: {
                                show: true,
                                when: "name",
                                eq: "",
                              },
                            },
                            actions: [
                              {
                                name: "field disabled",
                                type: "property",
                                property: {
                                  label: "Disabled",
                                  value: "disabled",
                                  type: "boolean",
                                },
                                state: true,
                              },
                            ],
                          },
                        ],
                        attributes: {},
                        overlay: {
                          style: "",
                          page: "",
                          left: "",
                          top: "",
                          width: "",
                          height: "",
                        },
                        type: "dmn",
                        input: true,
                        dmnXML:
                          '<?xml version="1.0" encoding="UTF-8"?>\n        <definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" id="definitions" name="definitions" namespace="http://camunda.org/schema/1.0/dmn">\n          <decision id="decision" name="Check Order">\n            <decisionTable id="decisionTable">\n              <input id="InputClause_0a0smkt">\n                <inputExpression id="LiteralExpression_1ik0pio" typeRef="string">\n                  <text></text>\n                </inputExpression>\n              </input>\n              <output id="OutputClause_1jaj36j" typeRef="string" />\n            </decisionTable>\n          </decision>\n        </definitions>',
                        prefix: "",
                        suffix: "",
                        refreshOn: "",
                        dataGridLabel: false,
                        widget: null,
                        showCharCount: false,
                        showWordCount: false,
                        allowMultipleMasks: false,
                        addons: [],
                        id: "ebwbzxp",
                        defaultValue: null,
                      },
                      {
                        type: "button",
                        label: "Submit",
                        key: "submit",
                        size: "md",
                        block: false,
                        action: "submit",
                        disableOnInvalid: true,
                        theme: "primary",
                        id: "e9tukc9",
                        input: true,
                        placeholder: "",
                        prefix: "",
                        customClass: "",
                        suffix: "",
                        multiple: false,
                        defaultValue: null,
                        protected: false,
                        unique: false,
                        persistent: false,
                        hidden: false,
                        clearOnHide: true,
                        refreshOn: "",
                        redrawOn: "",
                        tableView: false,
                        modalEdit: false,
                        dataGridLabel: true,
                        labelPosition: "top",
                        description: "",
                        errorLabel: "",
                        tooltip: "",
                        hideLabel: false,
                        tabindex: "",
                        disabled: false,
                        autofocus: false,
                        dbIndex: false,
                        customDefaultValue: "",
                        calculateValue: "",
                        calculateServer: false,
                        widget: {
                          type: "input",
                        },
                        attributes: {},
                        validateOn: "change",
                        validate: {
                          required: false,
                          custom: "",
                          customPrivate: false,
                          strictDateValidation: false,
                          multiple: false,
                          unique: false,
                        },
                        conditional: {
                          show: null,
                          when: null,
                          eq: "",
                        },
                        overlay: {
                          style: "",
                          left: "",
                          top: "",
                          width: "",
                          height: "",
                        },
                        allowCalculateOverride: false,
                        encrypted: false,
                        showCharCount: false,
                        showWordCount: false,
                        properties: {},
                        allowMultipleMasks: false,
                        addons: [],
                        leftIcon: "",
                        rightIcon: "",
                      },
                    ],
                    title: "Last",
                    type: "panel",
                    tableView: false,
                    label: "Panel",
                  },
                  {
                    type: "button",
                    disableOnInvalid: true,
                    key: "submit",
                    tableView: false,
                    label: "Submit",
                    input: true,
                  },
                ],
                owner: "55673dc04f0405dd28205bb7",
                submissionAccess: [
                  { roles: ["5692b920d1028f01000407e6"], type: "create_own" },
                  { roles: [], type: "create_all" },
                  { roles: [], type: "read_own" },
                  { roles: ["5692b920d1028f01000407e6"], type: "read_all" },
                  { roles: [], type: "update_own" },
                  { roles: [], type: "update_all" },
                  { roles: [], type: "delete_own" },
                  { roles: [], type: "delete_all" },
                  { roles: [], type: "team_read" },
                  { roles: [], type: "team_write" },
                  { roles: [], type: "team_admin" },
                ],
                access: [
                  { roles: [], type: "create_own" },
                  { roles: [], type: "create_all" },
                  { roles: [], type: "read_own" },
                  {
                    roles: [
                      "5692b920d1028f01000407e4",
                      "5692b920d1028f01000407e5",
                      "5692b920d1028f01000407e6",
                    ],
                    type: "read_all",
                  },
                  { roles: [], type: "update_own" },
                  { roles: [], type: "update_all" },
                  { roles: [], type: "delete_own" },
                  { roles: [], type: "delete_all" },
                  { roles: [], type: "team_read" },
                  { roles: [], type: "team_write" },
                  { roles: [], type: "team_admin" },
                ],
                tags: ["common"],
                settings: {
                  controller:
                    "['$scope', function($scope) { $scope.$watch('submission.data', function(data) { console.log(data); }, true); }]",
                },
                revisions: "",
                _vid: 0,
                controller: "",
                properties: {},
                plan: "commercial",
              }}
            />
          </div>
        </Col>
      </Row>
    </>
  );
};
export default WizardForm;
